INSERT INTO users (phone,password,role) VALUES ('0000000000', 'password', 'admin');
INSERT INTO users (phone,password,role,device_token) VALUES ('1111111111', 'password', 'passenger', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('1111111112', 'password', 'passenger', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('1111111113', 'password', 'passenger', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('1111111114', 'password', 'passenger', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('1111111115', 'password', 'passenger', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('2222222221', 'password', 'driver', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('2222222222', 'password', 'driver', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('2222222223', 'password', 'driver', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('2222222224', 'password', 'driver', 'device_token');
INSERT INTO users (phone,password,role,device_token) VALUES ('2222222225', 'password', 'driver', 'device_token');