// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"time"
)

type User struct {
	ID          int64     `json:"id"`
	Phone       string    `json:"phone"`
	Password    string    `json:"password"`
	Name        string    `json:"name"`
	DateOfBirth time.Time `json:"date_of_birth"`
	Verified    bool      `json:"verified"`
	CreatedAt   time.Time `json:"created_at"`
}
